theme: jekyll-theme-minimal
title: When something is important enough, you do it even if the odds are not in your favor.
Description: Alan Marin De Luna
logo: /logo.jfif
Author:
  name: Alan Marin
  email: "alanmarin1996@gmail.com"